version: '3.7'

services:
#Drone services
  drone-server:
    image: drone/drone:0.8
    networks:
      - private
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./drone-data:/var/lib/drone/
    env_file:
      - ./drone.env
    restart: always 
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost:8000
      - DRONE_GITHUB=true
      - DRONE_DEBUG=false
      - DRONE_GITHUB_CLIENT=b0591ee4b18c2504e26d
      - DRONE_GITHUB_SECRET=7aea76d45c91a307d4f0315981f2a03a2b3f95fa
      - DRONE_SECRET=sstest

    drone-agent:
      image: drone/agent:0.8
      command: agent
      restart: always
      networks:
        - private
      depends_on:
        - drone-server
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
       env_file:
         - ./drone.env
       enviroment:
         - DRONE_SERVER=drone-server:9000
         - DRONE_SECRET=sstest


     minio:
       image: minio/minio
     volumes:
       - /tmp/data/:/export
       - /tmp/config/:root/.minio
     networks:
       - private
     depends_on:
      - drone-server
     ports:
       - "9001:9000"
     environment:
        MINIO_ACCESS_KEY: minio
        MINIO_SECRET_KEY: minio124
     command: server /export

networks:
  private: 
